### ISSUE TITLE
Fix Plis To New

### ISSUE THREAD

**Issue by fostdai** [skyss0fly/MultiVersionPM4#10]
Bro Plis Update Api Plis To Edit Api 4.6.0 to 4.7.0
@skyss0fly #

**Comment by skyss0fly** [comment]
you got it, im working on it
________________________________
From: fostdai ***@***.***>
Sent: Sunday, 14 August 2022 11:38 PM
To: skyss0fly/MultiVersionPM4 ***@***.***>
Cc: skyss0fly ***@***.***>; Mention ***@***.***>
Subject: [skyss0fly/MultiVersionPM4] Fix Plis To New (Issue #10)


Bro Plis Update Api Plis To Edit Api 4.6.0 to 4.7.0
@skyss0fly<https://github.com/skyss0fly> #
